#version: "3.7"
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: "gs"
      MONGO_INITDB_ROOT_PASSWORD: "gs"
      MONGO_INITDB_DATABASE: "root-db"

    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
